services:
  - type: web
    name: flicksync
    env: python
    plan: free
    buildCommand: "pip install -r Flicksync-main/requirement.txt && python notebooks/generate_recommendations.py && cd Flicksync-main/flicksync && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "cd Flicksync-main/flicksync && gunicorn cinesense.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
